from kivy.uix.screenmanager import Screen
from kivy.clock import Clock

from supabase_client import supabase
from realtime_helper import subscribe_postgres, unsubscribe_channel
from fruit_game_panel import FruitGamePanel

AGORA_APP_ID = "0df15e97a5b7423bbb0090bf560c9177"


class VoiceRoomScreen(Screen):
    channel_name = None
    room_id = None
    is_muted = False
    rtc_engine = None
    participants_channel = None
    joined = False

    def join_channel(self, channel_name, room_id):
        self.cleanup_room(remove_participant=False)
        self.channel_name = channel_name
        self.room_id = room_id
        self.is_muted = False

        self.ids.room_status_label.text = f"داخل الغرفة: {channel_name}"

        if not self.add_current_user():
            self.ids.room_status_label.text = "تعذر تسجيل دخولك للغرفة"
            return

        self.joined = True
        self.ids.fruit_game.set_room(room_id)
        self.request_microphone_permission()
        self.load_participants()
        self.start_participants_realtime()
        self.init_agora_engine()

    def request_microphone_permission(self):
        try:
            from android.permissions import Permission, request_permissions
            request_permissions([Permission.RECORD_AUDIO])
        except Exception:
            pass

    def get_current_user(self):
        try:
            session = supabase.auth.get_session()
            return session.user if session and session.user else None
        except Exception:
            return None

    def get_current_user_id(self):
        user = self.get_current_user()
        return user.id if user else None

    def get_display_name(self):
        user = self.get_current_user()
        if not user:
            return "مستخدم"
        metadata = getattr(user, "user_metadata", {}) or {}
        return (
            metadata.get("display_name")
            or metadata.get("name")
            or getattr(user, "email", None)
            or "مستخدم"
        )

    def add_current_user(self):
        user_id = self.get_current_user_id()
        if not user_id or not self.room_id:
            return False
        try:
            supabase.table("room_participants").upsert(
                {
                    "room_id": self.room_id,
                    "user_id": user_id,
                },
                on_conflict="room_id,user_id",
            ).execute()
            return True
        except Exception as e:
            print(f"خطأ فـ دخول المشارك: {e}")
            return False

    def init_agora_engine(self):
        try:
            from jnius import autoclass
            RtcEngineConfig = autoclass("io.agora.rtc2.RtcEngineConfig")
            RtcEngine = autoclass("io.agora.rtc2.RtcEngine")
            PythonActivity = autoclass("org.kivy.android.PythonActivity")

            config = RtcEngineConfig()
            config.mAppId = AGORA_APP_ID
            config.mContext = PythonActivity.mActivity.getApplicationContext()
            self.rtc_engine = RtcEngine.create(config)
            self.rtc_engine.enableAudio()

            # Testing mode only. For production, replace None with a short-lived
            # token generated by a trusted server/Edge Function.
            self.rtc_engine.joinChannel(None, self.channel_name, "", 0)
        except Exception as e:
            print(f"Agora غير جاهزة في الـAPK الحالي: {e}")
            self.rtc_engine = None

    def toggle_mute(self):
        self.is_muted = not self.is_muted
        if self.rtc_engine:
            try:
                self.rtc_engine.muteLocalAudioStream(self.is_muted)
            except Exception as e:
                print(f"خطأ فـ mute: {e}")
        self.ids.mute_button.text = "🔇 مكتوم" if self.is_muted else "🎤 مفعّل"

    def on_leave(self):
        self.cleanup_room(remove_participant=True)

    def leave_channel(self):
        self.cleanup_room(remove_participant=True)
        self.manager.current = "rooms"

    def cleanup_room(self, remove_participant=True):
        self.stop_participants_realtime()

        if self.rtc_engine:
            try:
                self.rtc_engine.leaveChannel()
                self.rtc_engine.destroy()
            except Exception as e:
                print(f"خطأ فـ إغلاق Agora: {e}")
            self.rtc_engine = None

        if remove_participant and self.joined:
            self.remove_current_user()

        self.joined = False
        self.channel_name = None
        self.room_id = None
        if "fruit_game" in self.ids:
            self.ids.fruit_game.cleanup()

    def remove_current_user(self):
        user_id = self.get_current_user_id()
        if not user_id or not self.room_id:
            return
        try:
            supabase.table("room_participants").delete().eq(
                "room_id", self.room_id
            ).eq("user_id", user_id).execute()
        except Exception as e:
            print(f"خطأ فـ الخروج من الغرفة: {e}")

    def load_participants(self):
        if not self.room_id:
            return
        try:
            response = (
                supabase.table("room_participants")
                .select("id,user_id,joined_at")
                .eq("room_id", self.room_id)
                .order("joined_at", desc=False)
                .execute()
            )
            self.populate_participants_ui(response.data or [])
        except Exception as e:
            print(f"خطأ فـ جلب المشاركين: {e}")

    def populate_participants_ui(self, participants):
        names = {}
        try:
            ids = [p.get("user_id") for p in participants if p.get("user_id")]
            if ids:
                profiles = supabase.table("profiles").select("id,username").in_("id", ids).execute()
                names = {x.get("id"): (x.get("username") or "مستخدم") for x in (profiles.data or [])}
        except Exception:
            pass
        self.ids.participants_rv.data = [
            {"participant_name": names.get(p.get("user_id"), "مستخدم")}
            for p in participants
        ]

    def start_participants_realtime(self):
        self.stop_participants_realtime()
        if not self.room_id:
            return
        try:
            self.participants_channel = supabase.channel(
                f"room-participants-{self.room_id}"
            )
            subscribe_postgres(
                self.participants_channel,
                "*",
                "public",
                "room_participants",
                lambda payload: Clock.schedule_once(lambda dt: self.load_participants(), 0),
                filter_value=f"room_id=eq.{self.room_id}",
            )
        except Exception as e:
            print(f"تعذر تشغيل Realtime للمشاركين: {e}")

    def stop_participants_realtime(self):
        if self.participants_channel:
            unsubscribe_channel(self.participants_channel)
            self.participants_channel = None
